name: Notify New Upstream Release

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 06:00 UTC
  workflow_dispatch:

jobs:
  check-upstream-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get latest upstream release
        id: get_release
        run: |
          latest=$(curl -s https://api.github.com/repos/syslog-ng/syslog-ng/releases/latest | jq -r .tag_name)
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Get last notified version
        id: get_last
        run: |
          last=$(gh issue list --label upstream-release --state all --json title --jq '.[].title' | grep -Eo 'syslog-ng [^ ]+' | head -n1 | awk '{print $2}')
          echo "last_tag=$last" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open issue if new release
        if: steps.get_release.outputs.latest_tag != steps.get_last.outputs.last_tag
        run: |
          gh issue create \
            --title "syslog-ng ${{ steps.get_release.outputs.latest_tag }} released" \
            --body "A new upstream release of syslog-ng is available: https://github.com/syslog-ng/syslog-ng/releases/tag/${{ steps.get_release.outputs.latest_tag }}" \
            --label upstream-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
